### ISSUE TITLE
Typo: in README step 11 Analyze the results URL should be engg-insights?

### ISSUE THREAD

**Issue by scottdangelo** [IBM/engineering-insights-composite-pattern#17]
In the README step 11 Analyze the results, the url is listed as
```
URL: http://<NODERED_BASE_URL>/engginsights.
```
But in node-red-flow/orchestrate_dsx_workflow.json
```
"url":"/engg-insights",
```

Is this a typo?

**Comment by balajikadambi** [comment]
Yes Scott. Its a typo. It should be engg-insights. Have changed it.
